import yfinance as yf  # type: ignore
import pandas as pd
from datetime import datetime

# Dictionary of stock names with NSE tickers (in the exact order you provided)
stocks = {
    "360ONE": "360ONE.NS",
    "ABB": "ABB.NS",
    "ABCAPITAL": "ABCAPITAL.NS",
    "ADANIENSOL": "ADANIENSOL.NS",
    "ADANIENT": "ADANIENT.NS",
    "ADANIGREEN": "ADANIGREEN.NS",
    "ADANIPORTS": "ADANIPORTS.NS",
    "ALKEM": "ALKEM.NS",
    "AMBER": "AMBER.NS",
    "Ambuja Cement": "AMBUJACEM.NS",
    "ANGELONE": "ANGELONE.NS",
    "APLAPOLLO": "APLAPOLLO.NS",
    "APOLLOHOSP": "APOLLOHOSP.NS",
    "Ashok Leyland": "ASHOKLEY.NS",
    "ASIANPAINT": "ASIANPAINT.NS",
    "ASTRAL": "ASTRAL.NS",
    "AUBANK": "AUBANK.NS",
    "AUROPHARMA": "AUROPHARMA.NS",
    "Axis bank": "AXISBANK.NS",
    "BAJAJ-AUTO": "BAJAJ-AUTO.NS",
    "BAJAJFINSV": "BAJAJFINSV.NS",
    "BAJFINANCE": "BAJFINANCE.NS",
    "Bandhan bank": "BANDHANBNK.NS",
    "Bank of Baroda": "BANKBARODA.NS",
    "BANKINDIA": "BANKINDIA.NS",
    "BDL": "BDL.NS",
    "BEL": "BEL.NS",
    "Bharat Forage": "BHARATFORG.NS",
    "BHARTIARTL": "BHARTIARTL.NS",
    "Bhel": "BHEL.NS",
    "BIOCON": "BIOCON.NS",
    "BLUESTARCO": "BLUESTARCO.NS",
    "BOSCHLTD": "BOSCHLTD.NS",
    "BPCL": "BPCL.NS",
    "BRITANNIA": "BRITANNIA.NS",
    "BSE": "BSE.NS",
    "CAMS": "CAMS.NS",
    "CANBK": "CANBK.NS",
    "CDSL": "CDSL.NS",
    "CGPOWER": "CGPOWER.NS",
    "CHOLAFIN": "CHOLAFIN.NS",
    "CIPLA": "CIPLA.NS",
    "Coal India": "COALINDIA.NS",
    "COFORGE": "COFORGE.NS",
    "COLPAL": "COLPAL.NS",
    "Container corporation": "CONCOR.NS",
    "Crompton greaves": "CROMPTON.NS",
    "CUMMINSIND": "CUMMINSIND.NS",
    "CYIENT": "CYIENT.NS",
    "Dabur": "DABUR.NS",
    "DALBHARAT": "DALBHARAT.NS",
    "Delhivery": "DELHIVERY.NS",
    "DIVISLAB": "DIVISLAB.NS",
    "DIXON": "DIXON.NS",
    "DLF": "DLF.NS",
    "DMART": "DMART.NS",
    "DRREDDY": "DRREDDY.NS",
    "Eicher motors": "EICHERMOT.NS",
    "Exide industries": "EXIDEIND.NS",
    "Federal bank": "FEDERALBNK.NS",
    "FORTIS": "FORTIS.NS",
    "GAIL": "GAIL.NS",
    "GLENMARK": "GLENMARK.NS",
    "GMRAIRPORT": "GMRAIRPORT.NS",
    "GODREJCP": "GODREJCP.NS",
    "GODREJPROP": "GODREJPROP.NS",
    "GRASIM": "GRASIM.NS",
    "HAL": "HAL.NS",
    "HAVELLS": "HAVELLS.NS",
    "HCLTECH": "HCLTECH.NS",
    "HDFCAMC": "HDFCAMC.NS",
    "HDFCBANK": "HDFCBANK.NS",
    "HDFCLIFE": "HDFCLIFE.NS",
    "HEROMOTOCO": "HEROMOTOCO.NS",
    "HFCL": "HFCL.NS",
    "HINDALCO": "HINDALCO.NS",
    "HINDUNILVR": "HINDUNILVR.NS",
    "Hindustan zinc": "HINDZINC.NS",
    "Hudco": "HUDCO.NS",
    "ICICIBANK": "ICICIBANK.NS",
    "ICICIGI": "ICICIGI.NS",
    "ICICI Prudential": "ICICIPRULI.NS",
    "Idea": "IDEA.NS",
    "IDFCFIRSTB": "IDFCFIRSTB.NS",
    "IEX": "IEX.NS",
    "IGL": "IGL.NS",
    "IIFL": "IIFL.NS",
    "INDHOTEL": "INDHOTEL.NS",
    "INDIANB": "INDIANB.NS",
    "INDIGO": "INDIGO.NS",
    "INDUSINDBK": "INDUSINDBK.NS",
    "Indus tower": "INDUSTOWER.NS",
    "INFY": "INFY.NS",
    "INOXWIND": "INOXWIND.NS",
    "IOC": "IOC.NS",
    "IRCTC": "IRCTC.NS",
    "IREDA": "IREDA.NS",
    "Irfc": "IRFC.NS",
    "ITC": "ITC.NS",
    "JINDALSTEL": "JINDALSTEL.NS",
    "JIOFIN": "JIOFIN.NS",
    "JSWENERGY": "JSWENERGY.NS",
    "JSWSTEEL": "JSWSTEEL.NS",
    "JUBLFOOD": "JUBLFOOD.NS",
    "Kalyan jeweller": "KALYANKJIL.NS",
    "KAYNES": "KAYNES.NS",
    "KEI": "KEI.NS",
    "KFINTECH": "KFINTECH.NS",
    "KOTAKBANK": "KOTAKBANK.NS",
    "KPITTECH": "KPITTECH.NS",
    "Laurus labs": "LAURUSLABS.NS",
    "LIC housing finance": "LICHSGFIN.NS",
    "LICI": "LICI.NS",
    "LODHA": "LODHA.NS",
    "LT": "LT.NS",
    "LT Finance": "LTF.NS",
    "LTIM": "LTIM.NS",
    "LUPIN": "LUPIN.NS",
    "M&M": "M&M.NS",
    "MANAPPURAM": "MANAPPURAM.NS",
    "MANKIND": "MANKIND.NS",
    "Marico": "MARICO.NS",
    "MARUTI": "MARUTI.NS",
    "MAXHEALTH": "MAXHEALTH.NS",
    "MAZDOCK": "MAZDOCK.NS",
    "MCX": "MCX.NS",
    "MFSL": "MFSL.NS",
    "MOTHERSON": "MOTHERSON.NS",
    "MPHASIS": "MPHASIS.NS",
    "MUTHOOTFIN": "MUTHOOTFIN.NS",
    "NATIONALUM": "NATIONALUM.NS",
    "NAUKRI": "NAUKRI.NS",
    "NBCC": "NBCC.NS",
    "NCC": "NCC.NS",
    "NESTLEIND": "NESTLEIND.NS",
    "NHPC": "NHPC.NS",
    "NMDC": "NMDC.NS",
    "NTPC": "NTPC.NS",
    "NUVAMA": "NUVAMA.NS",
    "NYKAA": "NYKAA.NS",
    "Oberoi reality": "OBEROIRLTY.NS",
    "OFSS": "OFSS.NS",
    "OIL": "OIL.NS",
    "ONGC": "ONGC.NS",
    "PAGEIND": "PAGEIND.NS",
    "PATANJALI": "PATANJALI.NS",
    "PAYTM": "PAYTM.NS",
    "PERSISTENT": "PERSISTENT.NS",
    "PETRONET": "PETRONET.NS",
    "PFC": "PFC.NS",
    "PGEL": "PGEL.NS",
    "PHOENIXLTD": "PHOENIXLTD.NS",
    "PIDILITIND": "PIDILITIND.NS",
    "PIIND": "PIIND.NS",
    "PNB": "PNB.NS",
    "PNBHOUSING": "PNBHOUSING.NS",
    "POLICYBZR": "POLICYBZR.NS",
    "POLYCAB": "POLYCAB.NS",
    "POWERGRID": "POWERGRID.NS",
    "PPLPHARMA": "PPLPHARMA.NS",
    "PRESTIGE": "PRESTIGE.NS",
    "Rbl bank": "RBLBANK.NS",
    "REC": "RECLTD.NS",
    "Reliance": "RELIANCE.NS",
    "Rail Vikas Nigam": "RVNL.NS",
    "SAIL": "SAIL.NS",
    "SAMMAANCAP": "SAMMAANCAP.NS",
    "SBICARD": "SBICARD.NS",
    "SBILIFE": "SBILIFE.NS",
    "SHREECEM": "SHREECEM.NS",
    "SHRIRAMFIN": "SHRIRAMFIN.NS",
    "SIEMENS": "SIEMENS.NS",
    "SOLARINDS": "SOLARINDS.NS",
    "SONACOMS": "SONACOMS.NS",
    "SRF": "SRF.NS",
    "SUNPHARMA": "SUNPHARMA.NS",
    "SUPREMEIND": "SUPREMEIND.NS",
    "SUZLON": "SUZLON.NS",
    "SYNGENE": "SYNGENE.NS",
    "TATACONSUM": "TATACONSUM.NS",
    "TATAELXSI": "TATAELXSI.NS",
    "Tata motors": "TATAMOTORS.NS",
    "TATAPOWER": "TATAPOWER.NS",
    "TATASTEEL": "TATASTEEL.NS",
    "TATATECH": "TATATECH.NS",
    "TCS": "TCS.NS",
    "TECHM": "TECHM.NS",
    "TITAGARH": "TITAGARH.NS",
    "TITAN": "TITAN.NS",
    "TORNTPHARM": "TORNTPHARM.NS",
    "TORNTPOWER": "TORNTPOWER.NS",
    "TRENT": "TRENT.NS",
    "TVSMOTOR": "TVSMOTOR.NS",
    "ULTRACEMCO": "ULTRACEMCO.NS",
    "UNIONBANK": "UNIONBANK.NS",
    "UNITDSPR": "UNITDSPR.NS",
    "UNOMINDA": "UNOMINDA.NS",
    "UPL": "UPL.NS",
    "VBL": "VBL.NS",
    "VEDL": "VEDL.NS",
    "VOLTAS": "VOLTAS.NS",
    "Wipro": "WIPRO.NS",
    "Yesbank": "YESBANK.NS",
    "Zomato": "ETERNAL.NS",
    "ZYDUSLIFE": "ZYDUSLIFE.NS"
}

# Fetch stock prices
stock_data_list = []
for stock_name, ticker in stocks.items():
    try:
        print(f"✅ Fetching data for {stock_name} ({ticker})...")
        stock_info = yf.Ticker(ticker)
        current_price = stock_info.history(period="1d")["Close"].iloc[-1]
        stock_data_list.append([stock_name, ticker, current_price])
    except Exception as e:
        print(f"❌ Failed to fetch data for {stock_name}: {e}")
        stock_data_list.append([stock_name, ticker, "N/A"])

# Convert to DataFrame
df = pd.DataFrame(stock_data_list, columns=["Stock", "Ticker", "Current Price"])

# Save with today's date
today_date = datetime.today().strftime("%d-%m-%Y")
file_name = f"current_stock_prices_{today_date}.xlsx"
df.to_excel(file_name, index=False, engine="openpyxl")

print(f"🔥 Stock prices saved to {file_name}!")
